### ISSUE TITLE
Icon for sortition component

### ISSUE THREAD

**Issue by xabier** [decidim/decidim-module-sortitions#1]
we use [open iconic set](https://useiconic.com/open) for icons. I was searching and the one I found that is most appropriate for this component is the Aperture one:

![image](https://user-images.githubusercontent.com/537284/34064525-e8ee15f8-e1f9-11e7-9e3a-269d94c727b1.png)

Unless @decidim/lot-px says otherwise move with this

**Comment by jsperezg** [comment]
The icons used for features are vector scalble (svg). Could somebody of your design team transform this PNG into an svg that can be used?

**Comment by javierarce** [comment]
@jsperezg they already have the SVG version in their site: https://useiconic.com/open-iconic/svg/aperture.svg :)
