### ISSUE TITLE
It should be possible to edit the sortition explanation once closed but nothing else

### ISSUE THREAD

**Issue by xabier** [decidim/decidim-module-sortitions#11]
# This is a Feature Proposal

## Description

Unless this is very hard to implement (in which case we leave this out for future development) it might be convenient to edit, once the sortition is created, ONLY the explanation field.

**Comment by jsperezg** [comment]
The issue #12 adds a new attribute called title. I assume that it should be editable as well.

**Comment by xabier** [comment]
Yes, good point
