### ISSUE TITLE
Cancel sortition

### ISSUE THREAD

**Issue by xabier** [decidim/decidim-module-sortitions#14]
# This is a Feature proposal

Mistakes can happen and a sortition might need to be canceled.

#### :tophat: Description

- [ ] An admin must be able to cancel a sortition
- [ ] Canceled sortitions need to have an explanation as to why they where canceled
- [ ] The sortition card (and it full information) needs to be listed, accessible to participants and visitors, identifyable as canceled, and containing: the explanation of its cancellation, all the content of the sortition (the same as a regular sortition) and the username of the admin that cancelled it.

**Comment by jsperezg** [comment]
This issue has been already fixed. The PR in charge of it was corrupted.
