### ISSUE TITLE
Why use `Decidim::Module`?

### ISSUE THREAD

**Issue by mrcasals** [decidim/decidim-module-sortitions#23]
This is neither a bug nor a feature request, it's a doubt. I see yon't this redundant?u're using a `Module` namespace for classes in this repo:

https://github.com/decidim/decidim-module-sortitions/blob/b253a05cc50c6326465b33d00d2676d32d14581f/app/models/decidim/module/sortitions/sortition.rb#L3-L7

Why use this? Isn't this redundant?

**Comment by mrcasals** [comment]
Ah, this issue might be related to this: https://github.com/decidim/decidim/issues/2396

**Comment by jsperezg** [comment]
Exactly, Xabier asked as switch to the new nomenclature

**Comment by mrcasals** [comment]
The nomenclature was just for the repo name. The gem name should be kept as `decidim-sortitions` (at least that's what the issue says)

**Comment by xabier** [comment]
> Exactly, Xabier asked as switch to the new nomenclature

Sorry for the misunderstanding, I was only talking about repo names
