### ISSUE TITLE
Soritition main page changes

### ISSUE THREAD

**Issue by xabier** [decidim/decidim-module-sortitions#26]
# This is a Feature Proposal

Revisiting the sortition page, the public page of a specific sortition, it doesn't look good, I thought we where going to add a page like the proposal page:

![image](https://user-images.githubusercontent.com/537284/34674742-5adff0ba-f487-11e7-89ed-febb54574375.png)

The title of the sortition should be the title (this is what I was asking on previous mockup revision). Also user, data, etc. should be equal to a proposal. The content should be the content of the current sortition page.

We need the right box with the following data:
* Instead of vote: X number of sortition results
* No vote box
* No follow box
* Reference: sortition ID here
* Claim and comment buttons will be added when ready by @decidim/lot-px 
* Share and Embed should be there as well

**Comment by xabier** [comment]
@decidim/lot-px anything to add?

**Comment by jsperezg** [comment]
The sortition has a reference. We're not showing it right now, but we can show it if you prefer it to a plain id.

With regards to the other parts, Adding share and embed features are pretty straight forward. What scares me are your comments about 'Claim and comments' buttons. What are supposed them to do? Are they part of the MVP?

**Comment by xabier** [comment]
Hi @jsperezg 

> What scares me are your comments about 'Claim and comments' buttons. What are supposed them to do? Are they part of the MVP?

I should have used the term "claim", it is called "adhesion/endorsement" right now. Don't worry with this, we are working with @decidim/lot-px and @decidim/lot-core and @decidim/lot-mods on a new set of actions for each decidim component/feature, this will also apply to `sortitions`

This action is been developed here: decidim/decidim#2343 and decidim/decidim#2287 based on your adhesion functionality for iniciatives, we are generalizing the functionality.

Regarding `comments` everything in Decidim should be open to comments. Cards are being redesigned to accommodate a standardized display of action buttons and counters, you can see it here:

* https://github.com/decidim/design/issues/155
* https://github.com/decidim/design/issues/156

This is not critical to the MVP right now but it is good to take the proposal template as a template for the sortition page, because this will make it easier to include this Endorsement and Comment buttons as the new design unfolds.

Sorry for not being explicit about this.
